[[redirects]]
  to = "/home"
  from = "/Home"
  status = 301
  force = false

[[redirects]]
  to = "/"
  from = "/Nosotros"
  status = 301
  force = false

[[redirects]]
  to = "/nosotros"
  from = "/Nosotrosp"
  status = 301
  force = false

[[redirects]]
  to = "/Header"
  from = "/HeaderComponents"
  status = 301
  force = false

[[redirects]]
  to = "/Dashboard"
  from = "/Dashboard"
  status = 301
  force = false

[[redirects]]
  to = "/AgregarUsuario"
  from = "/AgregarUsuario"
  status = 301
  force = false

[[redirects]]
  to = "/listausuario"
  from = "/ListUsuario"
  status = 301
  force = false

[[redirects]]
  to = "/login"
  from = "/LoginForm"
  status = 301
  force = false

[[redirects]]
  to = "/registro"
  from = "/RegistrationForm"
  status = 301
  force = false

[[redirects]]
  to = "/listacitas"
  from = "/ListCitas"
  status = 301
  force = false

[[redirects]]
  to = "/agregarcita"
  from = "/AgregarCita"
  status = 301
  force = false

[[redirects]]
  to = "/footer"
  from = "/FooterComponent"
  status = 301
  force = false

[[redirects]]
  to = "/nosotros"
  from = "/Nosotros"
  status = 301
  force = false

[[redirects]]
  to = "/agregarcita"
  from = "/AgregarCita"
  status = 301
  force = false

[[redirects]]
  to = "/principal"
  from = "/Paginap"
  status = 301
  force = false

[[redirects]]
  to = "/header2"
  from = "/HeaderPrincipalComponent"
  status = 301
  force = false

[[redirects]]
  to = "/catalogo"
  from = "/CatalogoServicios"
  status = 301
  force = false

[[redirects]]
  to = "/servicio"
  from = "/Servicio"
  status = 301
  force = false

[[redirects]]
  to = "/servicio/:id"
  from = "/ServicioDetalle"
  status = 301
  force = false

[[redirects]]
  to = "/corte"
  from = "/Cortepeloi"
  status = 301
  force = false

[[redirects]]
  to = "/manicura"
  from = "/UAs"
  status = 301
  force = false

[[redirects]]
  to = "/tintura"
  from = "/Tinturap"
  status = 301
  force = false
