# Archivo netlify.toml para redireccionamientos personalizados
[build]
  command = "npm run build"
  publish = "build/"
  
[[redirects]]
  from = "/home"
  to = "/home"
  status = 200

[[redirects]]
  from = "/"
  to = "/Nosotros"
  status = 200

[[redirects]]
  from = "/nosotros"
  to = "/Nosotrosp"
  status = 200

[[redirects]]
  from = "/Header"
  to = "/HeaderComponents"
  status = 200

[[redirects]]
  from = "/Dashboard"
  to = "/Dashboard"
  status = 200

[[redirects]]
  from = "/AgregarUsuario"
  to = "/AgregarUsuario"
  status = 200

[[redirects]]
  from = "/listausuario"
  to = "/ListUsuario"
  status = 200

[[redirects]]
  from = "/login"
  to = "/LoginForm"
  status = 200

[[redirects]]
  from = "/registro"
  to = "/RegistrationForm"
  status = 200

[[redirects]]
  from = "/listacitas"
  to = "/ListCitas"
  status = 200

[[redirects]]
  from = "/agregarcita"
  to = "/AgregarCita"
  status = 200

[[redirects]]
  from = "/footer"
  to = "/FooterComponent"
  status = 200

[[redirects]]
  from = "/nosotros"
  to = "/Nosotros"
  status = 200

[[redirects]]
  from = "/agregarcita"
  to = "/AgregarCita"
  status = 200

[[redirects]]
  from = "/principal"
  to = "/Paginap"
  status = 200

[[redirects]]
  from = "/header2"
  to = "/HeaderPrincipalComponent"
  status = 200

[[redirects]]
  from = "/catalogo"
  to = "/CatalogoServicios"
  status = 200

[[redirects]]
  from = "/servicio"
  to = "/Servicio"
  status = 200

[[redirects]]
  from = "/servicio/:id"
  to = "/ServicioDetalle"
  status = 200

[[redirects]]
  from = "/corte"
  to = "/Cortepeloi"
  status = 200

[[redirects]]
  from = "/manicura"
  to = "/UAs"
  status = 200

[[redirects]]
  from = "/tintura"
  to = "/Tinturap"
  status = 200
